package org.khjsdk.com.khjsdk_2020.value

data class InitString(
        val KBR_INIT: String = "EBGJFNBBKLJIGEJLEGGLFJEFHFMDHNNEGCFEBLCIBJJBLNLHCNAHCFOFGDLCJELIAMMKLBDFOGMAAACMJKNBIBAL:KHJBR001",//this for brazil 南美巴西
        val AISA_INIT: String = "EBGCFGBKKHJNGBJJEFHPFBENHLNBHAMGHOEIANDIBOINKHLBCCBDCHOCHOKLJLKIBNNILECMPPNHAP:KHJAISA001",//this for AISA 亚洲
        val EUR_INIT: String = "EDGGFCBNKNJHGLJEEEGFFHEIHNMMHCNLGGFABJCAAGJBLJLHDLAOCDOPGJLKIKLJANMNKBDKOPMGBMCOIG:KEUROPE001",//this for europe 欧洲
        val USA_INIT: String = "EBGEFABMKGJOGCJNEMGLFJEFHCMDHNNGHGFMBBDOAHJDLKKODNALCAPIGHLFIFLPBHNCKFDLPHNKBGDI:KUSAKEY001",//this for USA 北美
        val CN_INIT: String = "EBGEEHBHKOJHHNJNEMGNFPEJHNNHHENNGKFMBCDNAHJBLLKPDMAMCCPKGBLCJFLJAOMPLEDAODMEAGCKJMNGIHAN:KHJTEC001"//this for china 国内
)